apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deployment
  labels:
    app: abc-tech-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-tech-app

  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
      - name: abc-tech-app
        image: simoganger/abc-technologies:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1