---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Managed Prometheus
      type: prometheus
      url: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-3f8cc59e-f395-432e-af0d-0ff1f2259708
      jsonData:
        sigV4Auth: true
        sigV4Region: us-east-1
        sigV4AuthType: default
